### ISSUE TITLE
Delete button does not gain focus

### ISSUE THREAD

**Issue by mburri** [headwirecom/jsonforms-react-spectrum-renderers#45] opened 2020-12-01 07:23 UTC
Example: 1265 Array

The delete button does not gain focus when "Tab" is pressed - in fact - tabbing does not work at all

**Comment by hupf** [comment] 2020-12-01 16:45
This expected behavior should just work without having to specify anything on our side. They are just HTML `<button>` elements and as long as they have no `tabindex="-1"` (which they don't) they should receive focus . And also: it works with buttons outside of a table.

I've created an isolated test app, with a React Spectrum Table component and React Spectrum Button components in a row and can observe the same behavior: the row is focused, the buttons are ignored in the tab cycle. It might either be intentional to only cycle through the rows and not their contents, or it might be a bug. Actually I think it's the latter and might be caused by some positioning styles of the Table component.

I think we're hunting bugs of the React Spectrum Table component here, which is not yet released (alpha).

**Comment by reusr1** [comment] 2020-12-09 14:30
@hupf @mburri closing this issue as the navigation in the table from field to field is done by using cursor keys in react spectrum an not tab

**Closed as completed by reusr1** 2020-12-09 14:30 UTC
